### ISSUE TITLE
Add these please :)

### ISSUE THREAD

**Issue by xX420MCplayerXx** [Jacobw0/Jacobw0.github.io#1]
https://youtu.be/ut3n8-9JM5o?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/QbRkKO3xzQ8?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/dwbBjtYCJNQ?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/QMaDaaL7S-c?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/lIDu72rGs50?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/TShomFm6CUI?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/uW2ppKluUPs?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/YLhkZ4-xcoE?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/wYMG-6tpoiw?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/Jt_5O4cJGMg?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/SMXG2j_q_0Q?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/gNiThpb5U8o?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/isfvb5ZDOCw?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/cxRVgo3-l54?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/AnxENvJi6Jg?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://youtu.be/ZsUAK9cWIJ8?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS
https://www.youtube.com/watch?v=IOy9SuAFkgY
https://www.youtube.com/watch?v=fIfMOGUi98Y
https://www.youtube.com/watch?v=YJey74gmkLY
https://www.youtube.com/watch?v=Y7WtkdLQ6PM
https://www.youtube.com/watch?v=oJnflRxEAwc
https://www.youtube.com/watch?v=jBUyINJEfkY
https://www.youtube.com/watch?v=K3DlpL1SFwM
https://www.youtube.com/watch?v=95_33ItUC9k
https://www.youtube.com/watch?v=z6P9Kzy_3IU
https://www.youtube.com/watch?v=ngGtRRqJlOs
https://www.youtube.com/watch?v=aYTRBt0aNbM
https://www.youtube.com/watch?v=_lFUbTZiHjY
https://www.youtube.com/watch?v=qfIFsCwh1MM

**Comment by GlitchyZorua** [comment]
oh my god ok

**Comment by xX420MCplayerXx** [comment]
part 2 comming soon :)
